Repository NextCitizens/ncs_core, pull requests merged in 2022-06, with the labels that each got.

#102 Create randomTable.lua
  src/api/tables/shared/randomTable.lua
Labels: Improvement

#105 Add string split function
  src/api/player/server/getPlayerIdentifiers.lua
  src/api/strings/shared/split.lua
Labels: Feature

#108 :recycle: New function and fixes
  src/api/player/client/show3DText.lua
  src/api/streaming/client/requestAnimDict.lua
  src/api/streaming/client/requestAnimSet.lua
  src/api/streaming/client/requestModel.lua
  src/api/streaming/client/requestNamedPtfxAsset.lua
  src/api/streaming/client/requestStreamedTextureDict.lua
  src/api/streaming/client/requestWeaponAsset.lua
  src/api/strings/shared/moneyFormat.lua
Labels: Bug, Feature

#138 🔨 Add some peds & vehicles functions
  src/api/ped/client/getHeading.lua
  src/api/ped/client/getHealth.lua
  src/api/ped/client/isDead.lua
  src/api/ped/client/kill.lua
  src/api/ped/client/leaveVehicle.lua
  src/api/ped/client/resetAlhpa.lua
  src/api/ped/client/setAlhpa.lua
  src/api/ped/client/setHealth.lua
  src/api/ped/client/setIntoVehicle.lua
  src/api/ped/client/setMaxHealth.lua
  src/api/vehicles/client/getDoorsStates.lua
  src/api/vehicles/client/getPlate.lua
  src/api/vehicles/client/lockVehicle.lua
  src/api/vehicles/client/openAllDoor.lua
  src/api/vehicles/client/openDoor.lua
  src/api/vehicles/client/unlockVehicle.lua
Labels: Feature

#149 🐛 Add many math functions with time
  src/api/maths/shared/addTimeToUnix.lua
  src/api/maths/shared/getDateByUnixTime.lua
  src/api/maths/shared/unformatTime.lua
Labels: Feature

#153 :sparkles: Add other database functions
  src/api/database/server/async_insert.lua
  src/api/database/server/async_query.lua
  src/api/database/server/async_scalar.lua
  src/api/database/server/async_single.lua
  src/api/database/server/async_update.lua
  src/api/database/server/scalar.lua
  src/api/database/server/single.lua
  src/api/database/server/update.lua
Labels: Feature

#152 🦖 - Add ban/unban modules + translations.
  src/api/player/server/kickPlayer.lua
  src/api/strings/shared/random.lua
  src/enum/requiredStartupStep.lua
  src/localization/locales/lang_de.lua
  src/localization/locales/lang_en.lua
  src/localization/locales/lang_es.lua
  src/localization/locales/lang_fr.lua
  src/localization/locales/lang_hu.lua
  src/localization/locales/lang_it.lua
  src/localization/locales/lang_pl.lua
  src/localization/locales/lang_ro.lua
  src/modules/players/server/events/onPlayerConnecting.lua
  src/modules/sanctions/_define.lua
  src/modules/sanctions/_export.lua
  src/modules/sanctions/server/events/banDBReady.lua
  src/modules/sanctions/server/functions/banPlayer.lua
  src/modules/sanctions/server/functions/banPlayerID.lua
  src/modules/sanctions/server/functions/isPlayerBan.lua
  src/modules/sanctions/server/functions/loadBanList.lua
  src/modules/sanctions/server/functions/unbanPlayer.lua
Labels: Feature

#154 Update database_scheme.sql ( add NCS_bans table )
  database_scheme.sql
Labels: Fix/Typo

#155 :hammer: API_Player setMarkerPosition
  src/api/player/client/setMarkerPosition.lua
Labels: Feature

#157 ✨API_Entity : Move files from API_Ped to API_Entity
  src/api/entity/_define.lua
  src/api/entity/_export.lua
  src/api/entity/client/getHeading.lua
  src/api/entity/client/getPosition.lua
  src/api/entity/client/getSpeed.lua
  src/api/entity/client/resetAlhpa.lua
  src/api/entity/client/setAlhpa.lua
  src/api/entity/client/setFreeze.lua
  src/api/entity/client/setHeading.lua
  src/api/entity/client/setHealth.lua
  src/api/entity/client/setPosition.lua
  src/api/entity/client/setVisible.lua
  src/api/ped/client/getHeading.lua
  src/api/ped/client/getPosition.lua
  src/api/ped/client/resetAlhpa.lua
  src/api/ped/client/setAlhpa.lua
  src/api/ped/client/setFreeze.lua
  src/api/ped/client/setHeading.lua
  src/api/ped/client/setHealth.lua
  src/api/ped/client/setVisible.lua
  src/api/vehicles/client/getSpeed.lua
Labels: Improvement

#164 🔨 Add NCSItems
  database_scheme.sql
  src/class/NCSItems/server/_constructor.lua
  src/class/NCSItems/server/functions/minify.lua
  src/modules/items/_define.lua
  src/modules/items/_export.lua
  src/modules/items/client/events/receiveItems.lua
  src/modules/items/client/function/set.lua
  src/modules/items/client/functions/addUsable.lua
  src/modules/items/client/functions/get.lua
  src/modules/items/client/functions/set.lua
  src/modules/items/client/functions/setDataItem.lua
  src/modules/items/client/functions/use.lua
  src/modules/items/client/main.lua
  src/modules/items/server/events/onDatabaseReady.lua
  src/modules/items/server/events/playerNowInGame.lua
  src/modules/items/server/functions/exists.lua
  src/modules/items/server/functions/get.lua
  src/modules/items/server/functions/getAll.lua
  src/modules/items/server/functions/set.lua
  src/modules/items/server/main.lua
Labels: Feature

#168 ✅ • Add Warn/Unwarn modules.
  src/enum/requiredStartupStep.lua
  src/modules/sanctions/_define.lua
  src/modules/sanctions/server/events/onDatabaseReady.lua
  src/modules/sanctions/server/functions/loadAllSanctions.lua
  src/modules/sanctions/server/functions/loadBanList.lua
  src/modules/sanctions/server/functions/unwarnPlayer.lua
  src/modules/sanctions/server/functions/warnPlayer.lua
  src/modules/sanctions/server/functions/warnPlayerID.lua
Labels: Feature

#161 🔨 Add error if source is invalid & ✏️ Put same typos
  src/api/player/server/getPlayerIdentifier.lua
  src/api/player/server/getPlayerIdentifiers.lua
  src/api/player/server/getPlayerLicense.lua
  src/api/player/server/getPlayerName.lua
  src/api/player/server/kickPlayer.lua
  src/api/vehicles/client/lockVehicle.lua
  src/api/vehicles/client/unlockVehicle.lua
Labels: Fix/Typo

#181 Fix skin
  src/api/tables/shared/indexUnformat.lua
  src/modules/skin/client/events/onInitializeCharacter.lua
  src/modules/skin/client/events/onSetSkin.lua
  src/modules/skin/client/functions/applySkin.lua
  src/modules/skin/client/main.lua
  src/modules/skin/server/events/savePlayerSkin.lua
  src/modules/skin/server/functions/setSkin.lua
Labels: Fix/Typo, To be tested

#171 ✨Add Death module
  database_scheme.sql
  src/api/player/client/spawn.lua
  src/class/NCSCharacter/server/_constructor.lua
  src/class/NCSCharacter/server/functions/minify.lua
  src/class/NCSCharacter/server/functions/save.lua
  src/class/NCSCharacter/server/functions/setDeathStatus.lua
  src/class/NCSPlayer/server/_constructor.lua
  src/class/NCSPlayer/server/functions/save.lua
  src/class/NCSPlayer/server/functions/setCharacterByIdentifier.lua
  src/core/events/client/kill.lua
  src/core/events/client/revive.lua
  src/core/server.lua
  src/localization/locales/lang_de.lua
  src/localization/locales/lang_en.lua
  src/localization/locales/lang_es.lua
  src/localization/locales/lang_fr.lua
  src/localization/locales/lang_hu.lua
  src/localization/locales/lang_it.lua
  src/localization/locales/lang_pl.lua
  src/localization/locales/lang_ro.lua
  src/modules/commands/server/killPlayer.lua
  src/modules/commands/server/revivePlayer.lua
  src/modules/players/server/events/onPlayerInitialized.lua
  src/modules/skin/client/events/onInitializeCharacter.lua
  type/NCSPlayerData.lua
Labels: Feature, To be tested

#188 Add IsEntityVisible function
  src/api/entity/client/isVisible.lua
Labels: Feature
