Repository NextCitizens/ncs_core, pull requests merged in 2022-05, with the labels that each got.

#7 _NCS Function for vehicle
  src/api/vehicles/client/deleteVehicle.lua
  src/api/vehicles/client/getVehicleProperties.lua
  src/api/vehicles/client/setVehicleProperties.lua
  src/api/vehicles/client/spawnVehicle.lua
Labels: enhancement

#6 ✨ Add _NCS#triggerClientEvent
  src/core/server.lua
Labels: enhancement

#9 :hammer: Add _NCS#getClosestPlayer
  src/api/players/getClosestPlayer.lua
  src/api/players/playAnimation.lua
Labels: enhancement

#11 🔨 Add _NCS#keyboardInput
  src/api/players/client/getClosestPlayer.lua
  src/api/players/client/keyboardInput.lua
Labels: enhancement

#8 :hammer: Add _NCS#registerNetEvent & _NCS#triggerEvent
  src/core/shared.lua
Labels: enhancement

#12 🔨 Add _NCS#groupDigits
  src/api/math/groupDigits.lua
  src/core/shared.lua
Labels: enhancement

#15 :hammer: Add _NCS#roundNumber
  src/api/math/roundNumber.lua
Labels: enhancement

#20 🔨 Add _NCS#playAnimation
  src/api/peds/client/playAnimation.lua
Labels: Feature

#39 🔨 Add target ped for API_PED:playAnimation
  src/api/ped/client/playAnimation.lua
Labels: Improvement

#38 :hammer: Add some notification function
  src/api/player/client/showAdvancedNotification.lua
  src/api/player/client/showHelpNotification.lua
  src/api/player/client/showMissionNotification.lua
  src/api/player/client/showNotification.lua
Labels: Feature

#42 🔨 Add API_Player:getName
  src/api/player/server/getPlayerName.lua
Labels: Feature

#33 🔨 Add _NCS#getVehicleStates
  src/api/vehicles/client/getVehicleStates.lua
Labels: Feature

#35 :sparkles: spawnVehicle Server
  src/api/vehicles/server/spawnVehicle.lua
Labels: Feature

#51 :recycle: Refactor fxmanifest
  fxmanifest.lua
Labels: Improvement

#48 ✨Add Miscellaneous additions
  src/api/objects/_define.lua
  src/api/objects/_export.lua
  src/api/objects/server/serverCreateObject.lua
  src/api/player/client/show3DText.lua
  src/api/player/client/showKeyboard.lua
  src/api/player/client/showSubtitle.lua
Labels: Feature

#50 :hammer: Update SpawnVehicle
  src/api/vehicles/server/spawnVehicle.lua
Labels: Improvement

#53 ✨ When a vehicle is repaired, the deformations can be reset.
  src/api/vehicles/client/repairVehicle.lua
Labels: Improvement

#61 🌐 First literals for lang_pl
  src/localization/locales/lang_pl.lua
Labels: Localization

#60 🌐 First literals for lang_es
  src/localization/locales/lang_es.lua
Labels: Localization

#65 🩹 Fix showKeyboard.
  src/api/player/client/showKeyboard.lua
Labels: Fix/Typo

#71 🐛 Fix MOD_Players bug
  fxmanifest.lua
Labels: Bug

#59 🌐 First literals for lang_de
  src/localization/locales/lang_de.lua
Labels: Localization

#70 🔨 edit api return param
  src/api/ped/client/playAnimation.lua
  src/api/vehicles/client/getVehicleProperties.lua
  src/api/vehicles/client/getVehicleStates.lua
  src/api/vehicles/client/spawnVehicle.lua
  src/api/vehicles/server/spawnVehicle.lua
Labels: Documentation

#68 🔨 Add _NCS.Vehicles:getClosest & _NCS.Vehicles:getVehicles & _NCS.Vehicles:getModel
  src/api/player/client/showAdvancedNotification.lua
  src/api/vehicles/client/getClosestVehicle.lua
  src/api/vehicles/client/getModel.lua
  src/api/vehicles/client/getVehicles.lua
  src/localization/locales/lang_it.lua
Labels: Feature

#81 :hammer:(API_Strings): fixed wrong param
  src/api/strings/shared/firstToUpper.lua
Labels: Bug

#72 :hammer: Add some scaleform functions
  src/api/scaleform/_define.lua
  src/api/scaleform/_export.lua
  src/api/scaleform/client/requestMovie.lua
  src/api/scaleform/client/showBigFreemodeMessage.lua
  src/api/scaleform/client/showBreakingNews.lua
  src/api/scaleform/client/showTrafficMovie.lua
Labels: Feature

#74 ✨ UI System
  .gitignore
  fxmanifest.lua
  src-web/.gitignore
  src-web/index.html
  src-web/package.json
  src-web/postcss.config.js
  src-web/src/App.tsx
  src-web/src/assets/index.css
  src-web/src/main.tsx
  src-web/src/providers/receiveNuiEvent.ts
  src-web/src/providers/sendNuiEvent.ts
  src-web/src/providers/visibility.tsx
  src-web/src/vite-env.d.ts
  src-web/tailwind.config.js
  src-web/tsconfig.json
  src-web/tsconfig.node.json
  src-web/vite.config.ts
  src/api/ui/_define.lua
  src/api/ui/_export.lua
  src/api/ui/client/registerAction.lua
  src/api/ui/client/sendAction.lua
Labels: Feature

#83 🔨 Add API_Player / API_Ped
  src/api/ped/client/getPosition.lua
  src/api/ped/client/setHeading.lua
  src/api/ped/client/setPosition.lua
  src/api/player/client/getPosition.lua
  src/api/player/client/setHeading.lua
  src/api/player/client/setPosition.lua
Labels: Feature

#84 :hammer: Fix undeclared table
  src/core/shared.lua
Labels: Bug

#85 Add API giveWeapon
  src/api/ped/client/giveWeapon.lua
  src/api/player/client/giveWeapon.lua
Labels: Feature

#89 :hammer: Add API_Player:setModel
  src/api/player/client/setModel.lua
Labels: Feature

#88 Add keybind api
  src/api/keybind/_define.lua
  src/api/keybind/_export.lua
  src/api/keybind/client/data.lua
  src/api/keybind/client/keybind.lua
  src/api/player/client/registerKeyBind.lua
Labels: Feature

#73 🔨 Add lots of things
  src/api/ped/client/getAllPeds.lua
  src/api/ped/client/getClosetPed.lua
  src/api/player/client/showFloatingHelpNotification.lua
  src/api/player/events/notify.lua
  src/api/player/server/getPlayerIdentifiers.lua
  src/class/Player/server/NCSPlayer.lua
  src/modules/players/server/functions/notifyAll.lua
Labels: Feature

#66 :sparkles: : Create Discord API
  src/api/discordBot/_define.lua
  src/api/discordBot/_export.lua
  src/class/Bot/server/NCSBot.lua
  src/enum/discordErrorType.lua
  src/enum/methodType.lua
  src/modules/bot/_define.lua
  src/modules/bot/server/_manager.lua
Labels: Feature

#96 :hammer: API_Ped Add give/has/remove WeaponComponent + fix
  src/api/ped/client/giveWeaponComponent.lua
  src/api/ped/client/hasWeapon.lua
  src/api/ped/client/hasWeaponComponent.lua
  src/api/ped/client/removeWeaponComponent.lua
Labels: Feature, Fix/Typo

#95 🎨 Add colorBg in notification event
  src/api/player/events/notify.lua
  src/class/Player/server/NCSPlayer.lua
Labels: Improvement

#97 ✏️ #API_Vehicles update function & news
  src/api/objects/server/createObject.lua
  src/api/objects/server/deleteObject.lua
  src/api/ped/client/getDistance.lua
  src/api/ped/server/deletePed.lua
  src/api/ped/server/spawnPed.lua
  src/api/vehicles/client/getClosestVehicle.lua
  src/api/vehicles/client/getFuelTank.lua
  src/api/vehicles/client/getSpeed.lua
  src/api/vehicles/client/getVehicleProperties.lua
  src/api/vehicles/client/setFuel.lua
  src/api/vehicles/client/setVehicleProperties.lua
Labels: Bug, Improvement

#100 :sparkles: Just added the 3d text
  src/api/player/client/show3DText.lua
Labels: Feature

#98 ✨Add streaming function / Fix spawnVehicle
  src/api/streaming/_define.lua
  src/api/streaming/_export.lua
  src/api/streaming/client/requestAnimDict.lua
  src/api/streaming/client/requestAnimSet.lua
  src/api/streaming/client/requestModel.lua
  src/api/streaming/client/requestNamedPtfxAsset.lua
  src/api/streaming/client/requestStreamedTextureDict.lua
  src/api/streaming/client/requestWeaponAsset.lua
  src/api/vehicles/client/spawnVehicle.lua
Labels: Feature, Improvement
